app/app/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views

try:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('api/health-check/', core_views.health_check,
             name='health-check'),
        path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
        path(
            'api/docs/',
            SpectacularSwaggerView.as_view(url_name='api-schema'),
            name='api-docs',
        ),
        path('api/user/', include('user.urls')),
        path('', include('stats.urls')),
    ]

    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
except Exception:
    urlpatterns = []

app/stats/urls.py
"""
Statistics URLs for the website
"""
from django.urls import path, include

from stats import views


app_name = 'stats'


# Backend URLs
backend_patterns = [
    path('list/<str:name>/', views.ListView.as_view(),
         name='api_list_view'),
    path('list/<str:name>/queries/<int:query_id>/',
         views.QueryListView.as_view(), name='api_list_query_view'),
    path('home/<str:name>/<int:id>/', views.HomeView.as_view(),
         name='api_home_view'),
    path('home/<str:name>/<int:id>/queries/<int:query_id>/',
         views.QueryHomeView.as_view(), name='api_home_query_view')
]

# Vanilla Django URLs
vanilla_patterns = [
    path('list/<str:name>/', views.list_view, name='list_view'),
    path('home/<str:name>/<int:id>/', views.concrete_view, name='home_view'),
    path('', views.home, name='home'),
]


urlpatterns = [
    # Backend URLs with '/api/' prefix
    path('api/', include(backend_patterns)),

    # Vanilla Django URLs without any prefix
    path('', include(vanilla_patterns)),
]

app/stats/views.py
"""
Views for statistics application (fullstack and backend)
"""
# base python imports
from django.db.models import QuerySet
from .datatypes import PageParts

# django imports
from django.shortcuts import render
from django.http import (
    Http404,
    HttpResponseNotFound,
)


# imports for DRF
from drf_spectacular.utils import (extend_schema_view,
                                   extend_schema,
                                   OpenApiParameter,
                                   OpenApiTypes)
from rest_framework import (
    status,
)
from rest_framework import generics
from rest_framework.response import Response

# import custom paginator
from .paginator import Paginator

# main local things
from .queries import ConcreteStatisticsFactory, ListStatisticsFactory
from .serializers import (GraphSerializer,
                          SingleDataListSerializer,
                          ListDataListsSerializer,
                          CustomValueSerializer)

from .models import (
    Country, League, Team, Player, Match
)


MODEL_IS_NOT_EXIST_ERRORS = (
    Country.DoesNotExist,
    League.DoesNotExist,
    Team.DoesNotExist,
    Player.DoesNotExist,
    Match.DoesNotExist
)


# DJANGO REST FRAMEWORK VIEWS
@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'name',
                OpenApiTypes.STR,
                description='Name of the statistics',
                location=OpenApiParameter.PATH
            )
        ]
    )
)
class ListView(generics.ListAPIView):
    """Show list of generic data"""
    def get_queryset(self):
        stats_type: str = self.kwargs.get('name')
        factory = ListStatisticsFactory(stats_type)
        queryset = factory.prepare_list()
        return queryset

    def list(self, request, *args, **kwargs):
        try:
            queryset = self.get_queryset()
            serializer = ListDataListsSerializer(queryset)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except IndexError:
            return Response({"error": "Index out of range"},
                            status=status.HTTP_404_NOT_FOUND)
        except KeyError:
            return Response({"error": "Key is not found"},
                            status=status.HTTP_404_NOT_FOUND)
        except AttributeError:
            return Response({"error": "This name is wrong"},
                            status=status.HTTP_404_NOT_FOUND)


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'name',
                OpenApiTypes.STR,
                description='Name of the statistics',
                location=OpenApiParameter.PATH
            ),
            OpenApiParameter(
                'query_id',
                OpenApiTypes.INT,
                description='ID of the query',
                location=OpenApiParameter.PATH
            )
        ]
    )
)
class QueryListView(generics.RetrieveAPIView):
    """Abstract base class for list views."""
    def get_object(self) -> QuerySet:
        stats_type: str = self.kwargs.get('name')
        query_id: int = int(self.kwargs.get('query_id'))
        factory = ListStatisticsFactory(stats_type)
        queryset: QuerySet = factory.prepare_graphs()[query_id]()
        return queryset

    def retrieve(self, request, *args, **kwargs):
        try:
            queryset = self.get_object()
            if queryset.page_part is PageParts.VISUAL:
                serializer = GraphSerializer(queryset)
            elif queryset.page_part is PageParts.ENTRANCE:
                serializer = CustomValueSerializer(queryset)
            else:
                return Response(status=status.HTTP_404_NOT_FOUND)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Http404:
            return Response({"error": "Query ID not found"},
                            status=status.HTTP_404_NOT_FOUND)
        except IndexError:
            return Response({"error": "Index out of range"},
                            status=status.HTTP_404_NOT_FOUND)
        except KeyError:
            return Response({"error": "name is not valid"},
                            status=status.HTTP_404_NOT_FOUND)
        except AttributeError:
            return Response({"error": "Name is not valid"},
                            status=status.HTTP_404_NOT_FOUND)


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'name',
                OpenApiTypes.STR,
                description='Name of the statistics',
                location=OpenApiParameter.PATH
            ),
            OpenApiParameter(
                'id',
                OpenApiTypes.INT,
                description='ID of the statistics',
                location=OpenApiParameter.PATH
            )
        ]
    )
)
class HomeView(generics.ListAPIView):
    """Serialization class for home views."""
    def get_object(self):
        stats_type = self.kwargs.get('name')
        id = int(self.kwargs.get('id'))
        factory = ConcreteStatisticsFactory(stats_type, id)
        queryset = factory.get_fields()
        return queryset

    def list(self, request, *args, **kwargs):
        try:
            queryset = self.get_object()
            # Create an instance of the serializer
            serializer = SingleDataListSerializer(queryset)
        except Http404:
            return Response({"error": "Query ID not found"},
                            status=status.HTTP_404_NOT_FOUND)
        except IndexError:
            return Response({"error": "Index out of range"},
                            status=status.HTTP_404_NOT_FOUND)
        except KeyError:
            return Response({"error": "Name is not valid"},
                            status=status.HTTP_404_NOT_FOUND)
        except MODEL_IS_NOT_EXIST_ERRORS:
            return Response({"error": "Object does not exists"},
                            status=status.HTTP_404_NOT_FOUND)
        # Return the serialized data
        return Response(serializer.data, status=status.HTTP_200_OK)


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'name',
                OpenApiTypes.STR,
                description='Name of the statistics',
                location=OpenApiParameter.PATH
            ),
            OpenApiParameter(
                'id',
                OpenApiTypes.INT,
                description='ID of the statistics',
                location=OpenApiParameter.PATH
            ),
            OpenApiParameter(
                'query_id',
                OpenApiTypes.INT,
                description='ID of the query',
                location=OpenApiParameter.PATH
            )
        ]
    )
)
class QueryHomeView(generics.RetrieveAPIView):
    def get_object(self) -> QuerySet:
        stats_type: str = self.kwargs.get('name')
        id: int = int(self.kwargs.get('id'))
        query_id: int = int(self.kwargs.get('query_id'))
        factory = ConcreteStatisticsFactory(stats_type, id)
        queryset: QuerySet = factory.prepare_graphs()[query_id]()
        return queryset

    def retrieve(self, request, *args, **kwargs):
        try:
            queryset = self.get_object()
            if queryset.page_part is PageParts.VISUAL:
                serializer = GraphSerializer(queryset)
            elif queryset.page_part is PageParts.ENTRANCE:
                serializer = CustomValueSerializer(queryset)
            else:
                return Response(status=status.HTTP_400_BAD_REQUEST)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Http404:
            return Response({"error": "Query ID not found"},
                            status=status.HTTP_404_NOT_FOUND)
        except IndexError:
            return Response({"error": "Index out of range"},
                            status=status.HTTP_404_NOT_FOUND)
        except KeyError:
            return Response({"error": "Name is not valid"},
                            status=status.HTTP_404_NOT_FOUND)
        except TypeError:
            return Response({"error": "Invalid type"},
                            status=status.HTTP_404_NOT_FOUND)
        except MODEL_IS_NOT_EXIST_ERRORS:
            return Response({"error": "Object does not exists"},
                            status=status.HTTP_404_NOT_FOUND)


# VANILA DJANGO VIEWS
def list_view(request, name: str):
    """Generalized approach of creating list views"""
    try:
        # Retrieve the queryset from ListStatisticsFactory
        statistics = ListStatisticsFactory(name).prepare_groups()
        name = statistics.name
        entrance = statistics.entrance
        visual = statistics.visual
        queryset = statistics.queryset

        # Paginate the queryset
        paginator = Paginator(queryset.data)
        page_number = int(request.GET.get('page') or 0)
        paginated_queryset = paginator.get_page(page_number)

        return render(request, 'list_view.html', {
            'queryset': paginated_queryset['data'],
            'paginator': paginated_queryset,
            'name': name,
            'entrance': entrance,
            'visual': visual,
        })
    except Exception as e:  # noqa
        # Handle other exceptions
        return HttpResponseNotFound(render(request, 'error_404.html'))


def concrete_view(request, name: str, id: int):
    """Generalized approach of creating concrete type views"""
    try:
        statistics = ConcreteStatisticsFactory(name, id).prepare_groups()
        return render(request, 'home_view.html', {'main': statistics,
                                                  'name': name,
                                                  'id': id})
    except Exception:
        # Handle other exceptions
        return HttpResponseNotFound(render(request, 'error_404.html'))

app/stats/templates/error_400.html
<!-- error_400.html (extends base.html) -->
{% extends 'base.html' %}

{% block title %}400 - Bad Request{% endblock %}

{% block content %}
    <div class="error-container">
        <h1>400 - Bad Request</h1>
        <p>Sorry, your request could not be processed.</p>
    </div>
{% endblock %}

app/stats/templates/error_403.html
<!-- error_403.html (extends base.html) -->
{% extends 'base.html' %}

{% block title %}403 - Forbidden{% endblock %}

{% block content %}
    <div class="error-container">
        <h1>403 - Forbidden</h1>
        <p>Sorry, you don't have permission to access this page.</p>
    </div>
{% endblock %}

app/stats/templates/error_404.html
<!-- error_404.html (extends base.html) -->
{% extends 'base.html' %}

{% block title %}404 - Not Found{% endblock %}

{% block content %}
    <div class="error-container">
        <h1>404 - Not Found</h1>
        <p>Sorry, the page you are looking for does not exist.</p>
    </div>
{% endblock %}

app/stats/templates/error_500.html
<!-- error_500.html (extends base.html) -->
{% extends 'base.html' %}

{% block title %}500 - Internal Server Error{% endblock %}

{% block content %}
    <div class="error-container">
        <h1>500 - Internal Server Error</h1>
        <p>Sorry, something went wrong on our end. Please try again later.</p>
    </div>
{% endblock %}

app/stats/templates/home.html
{% extends 'base.html' %}

{% block title %}Main page{% endblock %}

{% block content %}

{% endblock %}

app/stats/templates/home_view.html
{% extends 'base.html' %}

{% block title %}Home page of {{ name }}{% endblock %}

{% block content %}
    <!-- Entrance Section -->
    <section class="entrance-section">
        <div class="container">
            <h2>Entrance</h2>
            <div class="entrance-text">
                This is a homepage for {{ name }} with id {{ id }}.
                {% for item in main.entrance %}
                    {{ item.text }}.
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- Visualization Section -->
    {% if main.visual %}
        <section class="visualization-section">
            <div class="container">
                <h2 class="mb-4">Visualization</h2>
                <div class="row">
                    {% for graph in main.visual %}
                        <div class="col-lg-12 mb-4">
                            <div class="card bg-dark text-white">
                                <div class="card-body">
                                    <div class="plotly-graph">
                                        {{ graph.plot|safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    <!-- List Section -->
    <section class="single-element-section">
        <div class="container">
            <h2>{{ main.name }}</h2>
            <ul class="list-group">
                {% for field, value in main.fields %}
                    {% if value %}
                        <li class="list-group-item">
                            <strong>{{ field }}</strong>: {{ value }}
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

app/stats/templates/list_view.html
{% extends 'base.html' %}

{% block title %}List view of {{ name }}{% endblock %}

{% block content %}
    <!-- Entrance Section -->
    <section class="entrance-section">
        <div class="container">
            <h2>Entrance</h2>
            <div class="entrance-text">
                This is a list view for {{name}}.
                {% for item in entrance %}
                    {{ item.text }}.
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- Visualization Section -->
    {% if visual %}
        <section class="visualization-section">
            <div class="container">
                <h2 class="mb-4">Visualization</h2>
                <div class="row">
                    {% for graph in visual %}
                        <div class="col-lg-12 mb-4">
                            <div class="card bg-dark text-white">
                                <div class="card-body">
                                    <div class="plotly-graph">
                                        {{ graph.plot|safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    <!-- List Section -->
    <section class="list-section">
        <div class="container">
            <h2 class="section-title">List of {{ name }}s</h2>
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <ul class="list-group">
                        {% for item in queryset %}
                            <li class="list-group-item">
                                {% for field, value in item %}
                                    {% if value is not None %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <strong class="field-name">{{ field }}:</strong>
                                            </div>
                                            <div class="col-md-6">
                                                {% if field == 'Id' %}
                                                    <a href="{% url 'stats:home_view' name=name|lower id=value %}">{{ value }}</a>
                                                {% else %}
                                                    <span class="field-value">{{ value }}</span>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- Include pagination controls -->
    {% include 'pagination.html' %}
{% endblock %}