app/app/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views

try:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('api/health-check/', core_views.health_check,
             name='health-check'),
        path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
        path(
            'api/docs/',
            SpectacularSwaggerView.as_view(url_name='api-schema'),
            name='api-docs',
        ),
        path('api/user/', include('user.urls')),
        path('', include('stats.urls')),
    ]

    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
except Exception:
    urlpatterns = []

app/stats/urls.py
"""
Statistics URLs for the website
"""
from django.urls import path, include

from stats import views


app_name = 'stats'


# Backend URLs
backend_patterns = [
    path('list/<str:name>/', views.ListView.as_view(),
         name='api_list_view'),
    path('list/<str:name>/queries/<int:query_id>/',
         views.QueryListView.as_view(), name='api_list_query_view'),
    path('home/<str:name>/<int:id>/', views.HomeView.as_view(),
         name='api_home_view'),
    path('home/<str:name>/<int:id>/queries/<int:query_id>/',
         views.QueryHomeView.as_view(), name='api_home_query_view')
]

# Vanilla Django URLs
vanilla_patterns = [
    path('list/<str:name>/', views.list_view, name='list_view'),
    path('home/<str:name>/<int:id>/', views.concrete_view, name='home_view'),
    path('', views.home, name='home'),
]


urlpatterns = [
    # Backend URLs with '/api/' prefix
    path('api/', include(backend_patterns)),

    # Vanilla Django URLs without any prefix
    path('', include(vanilla_patterns)),
]

app/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Django Project{% endblock %}</title>
        <!-- Add the Google Fonts link -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
        <!-- Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        {% load static %}
        <link href="{% static 'styles.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Header -->
        <header class="header">
            <div class="container">
                <a href="{% url 'stats:home' %}">
                    <svg fill="#000000" version="1.1" id="ball" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="40" height="40" viewBox="0 0 40 40"
                        xml:space="preserve">
                        <g>
                            <path d="M15.796,0.049c-0.017,0-0.033,0.002-0.05,0.003c-0.017,0-0.033-0.003-0.05-0.003C7.028,0.049,0,7.076,0,15.745
                                s7.028,15.698,15.696,15.698c0.017,0,0.033-0.002,0.05-0.004c0.017,0,0.033,0.004,0.05,0.004c8.668,0,15.696-7.028,15.696-15.697
                                S24.464,0.049,15.796,0.049z M16.826,4.605l4.087-0.47c1.543,0.683,2.922,1.665,4.069,2.871l0.521,4.164l-5.051,1.327l-3.627-2.525
                                V4.605z M6.509,7.006c1.148-1.206,2.527-2.188,4.07-2.871l4.087,0.47v5.367l-3.627,2.525L5.988,11.17L6.509,7.006z M4.594,21.889
                                c-0.878-1.58-1.418-3.365-1.55-5.267l2.155-3.593l5.116,1.344l1.294,4.27l-3.331,4.965L4.594,21.889z M18.65,28.107
                                c-0.92,0.212-1.872,0.334-2.854,0.336c-0.017,0-0.033-0.002-0.05-0.002s-0.033,0.002-0.05,0.002
                                c-0.983-0.002-1.935-0.124-2.854-0.336l-2.885-3.411l3.254-4.847h2.535h2.535l3.254,4.847L18.65,28.107z M23.214,23.607
                                l-3.331-4.965l1.295-4.27l5.115-1.344l2.155,3.593c-0.132,1.901-0.673,3.687-1.55,5.267L23.214,23.607z"/>
                        </g>
                    </svg>
                </a>
                <h1>Welcome to Football Statistics</h1>
                <p>Explore the world of football with comprehensive statistics</p>
            </div>
        </header>

        <!-- Main content -->
        <main>
            <div class="container">
                <div class="row">
                    <!-- Sidebar -->
                    <aside class="col-md-3 sidebar">
                        <h2>Navigation</h2>
                        <!-- Sidebar content -->
                        <ul>
                            <li><a href="{% url 'stats:list_view' name='team' %}">Team List</a></li>
                            <li><a href="{% url 'stats:list_view' name='player' %}">Player List</a></li>
                            <li><a href="{% url 'stats:list_view' name='match' %}">Match List</a></li>
                            <li><a href="{% url 'stats:list_view' name='country' %}">Country List</a></li>
                            <li><a href="{% url 'stats:list_view' name='league' %}">League List</a></li>
                        </ul>
                    </aside>
                    <!-- Article -->
                    <article class="col-md-9 article-content">
                        {% block content %}
                        {% endblock %}
                    </article>
                </div>
            </div>
        </main>

        <!-- Footer -->
        <footer class="footer">
            <div class="container">
                <span class="text-muted">© 2016 Football Statistics</span>
            </div>
        </footer>

        <!-- jQuery, Popper.js, Bootstrap JS, Plotly -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </body>
</html>

app/templates/pagination.html
<!-- pagination.html -->
{% load mathfilters %}

<nav class="pagination">
    <ul class="pagination-list">
        <li class="pagination-item">
            <a class="page-link{% if not paginator.has_previous %} disabled{% endif %}" href="{% if paginator.has_previous %}?page=0{% endif %}">
                <span>&lt;&lt;</span> <!-- Link to first element -->
            </a>
        </li>
        <li class="pagination-item">
            <a class="page-link{% if not paginator.has_previous %} disabled{% endif %}" href="{% if paginator.has_previous %}?page={{ paginator.current_page|sub:1 }}{% endif %}">
                <span>&lt;</span> <!-- Link to previous element -->
            </a>
        </li>
        {% for i in paginator.page_range %}
            <li class="pagination-item">
                <a class="page-link{% if i == paginator.current_page %} active{% endif %}" href="?page={{ i }}">{{ i|add:1 }}</a>
            </li>
        {% endfor %}
        <li class="pagination-item">
            <a class="page-link{% if not paginator.has_next %} disabled{% endif %}" href="{% if paginator.has_next %}?page={{ paginator.current_page|add:1 }}{% endif %}">
                <span>&gt;</span> <!-- Link to next element -->
            </a>
        </li>
        <li class="pagination-item">
            <a class="page-link{% if not paginator.has_next %} disabled{% endif %}" href="{% if paginator.has_next %}?page={{ paginator.total_pages|sub:1 }}{% endif %}">
                <span>&gt;&gt;</span> <!-- Link to last element -->
            </a>
        </li>
    </ul>
</nav>